#!/usr/bin/env python3
"""
Green Curve — DAILY STALE-CONTENT CHECK, with bounded clearance.

Two jobs, deliberately separated by how reversible they are:

  REPORT  — anything whose staleness needs a judgement call: data that has aged
            past its refresh cadence, a page telling visitors a date the data no
            longer supports, a feed that stopped updating. Regenerating any of
            these costs money or changes published claims, so this script only
            says so. It never regenerates.

  CLEAR   — the one class of staleness that is safe to act on unattended:
            redundant BACKUP copies. `sync_cleaned_to_db.py` writes a new
            `greencurve.db.bak-<epoch>` on every run and nothing ever removes
            one, on a box with finite disk.

CLEARANCE IS DELIBERATELY HARD TO GET WRONG. A file is deleted only if it
passes EVERY guard:
  * it lives under the site root (no traversal, symlinks resolved)
  * its name matches an explicit backup pattern — never content
  * it is older than MIN_AGE_DAYS
  * at least KEEP_NEWEST newer siblings in its family survive
  * it is not the only copy of its family
Anything failing a guard is reported and kept. Dry-run is the default; the
timer passes --apply.

    python3 tools/stale_check.py            # report + dry-run clearance plan
    python3 tools/stale_check.py --apply    # actually delete (timer uses this)
    python3 tools/stale_check.py --json

Stdlib only.
"""
import argparse
import datetime as dt
import json
import os
import re
import sys
import time
from pathlib import Path

ROOT = Path("/var/www/greencurve")
if not ROOT.exists():
    ROOT = Path(r"c:/Viduti/esg-site")

STATUS_OUT = Path("/var/log/greencurve/stale_check.json")

# ── freshness policy ──────────────────────────────────────────────────────────
# max_age_days is "how old before a human should look", not a hard SLA.
FRESHNESS = [
    ("assets/data/esg_quotient.json", 45,
     "the published ESG universe; regenerate via the publishing-esg-data pipeline"),
    ("assets/data/esg_intelligence.json", 120,
     "drives the ESG Intelligence status indicator; regenerating calls the PAID "
     "Anthropic API — get a cost approved before running it"),
    ("assets/data/filing_tracker.json", 14,
     "weekly gc-filing-tracker timer; if stale the timer is failing"),
    ("posts/index.json", 7,
     "blog index; if stale the daily blog pipeline is silently failing"),
    ("sitemap.xml", 45, "regenerated by generate_company_pages.py"),
    ("feed.xml", 14, "RSS feed; server-owned"),
]

# ── clearance policy ──────────────────────────────────────────────────────────
BACKUP_PATTERNS = [
    re.compile(r"\.bak-\d+$"),          # greencurve.db.bak-1785673096
    re.compile(r"\.bak_\d{8}"),         # esg_quotient.bak_20260630_193925.json
    re.compile(r"\.bak-[0-9]{8}"),      # *.bak-20260801
    re.compile(r"\.\d{8}T\d{6}Z\.json\.bak$"),
    re.compile(r"\.json\.bak$"),
    re.compile(r"\.bak-pre-[a-z0-9-]+$"),
]
MIN_AGE_DAYS = 14        # never touch anything younger
KEEP_NEWEST = 5          # per family, always keep this many most-recent
MAX_DELETE_PER_RUN = 50  # a blast-radius cap; a runaway match cannot wipe a tree

findings = []
cleared, kept = [], []


def add(level, check, msg):
    findings.append({"level": level, "check": check, "message": msg})


def family_of(p: Path) -> str:
    """Group backups of the same origin file, so KEEP_NEWEST is per-origin."""
    n = p.name
    for pat in BACKUP_PATTERNS:
        n2 = pat.sub("", n)
        if n2 != n:
            return str(p.parent / n2)
    return str(p)


def is_backup(p: Path) -> bool:
    return any(pat.search(p.name) for pat in BACKUP_PATTERNS)


# ── [1] DATA FRESHNESS ────────────────────────────────────────────────────────
def check_freshness():
    print("\n[1] DATA FRESHNESS")
    now = time.time()
    for rel, max_days, note in FRESHNESS:
        p = ROOT / rel
        if not p.exists():
            print(f"    {rel:38} MISSING")
            add("WARN", "freshness", f"{rel} does not exist — {note}")
            continue
        age = (now - p.stat().st_mtime) / 86400
        mark = "OK" if age <= max_days else "STALE"
        print(f"    {rel:38} {age:6.1f}d  (limit {max_days}d)  [{mark}]")
        if age > max_days:
            add("WARN", "freshness",
                f"{rel} is {age:.0f} days old (limit {max_days}) — {note}")


# ── [2] PUBLISHED FRESHNESS CLAIMS ────────────────────────────────────────────
def parse_stamp(v):
    for fmt in ("%Y-%m-%dT%H:%M:%S.%f", "%Y-%m-%dT%H:%M:%S", "%Y-%m-%dT%H:%M:%S%z",
                "%Y-%m-%d", "%d %b %Y", "%d %B %Y"):
        try:
            d = dt.datetime.strptime(str(v).strip(), fmt)
            return d.date()
        except ValueError:
            continue
    return None


def check_claims():
    """A page that tells visitors a date the artifact no longer supports is a
    stale published CLAIM — the defect that had the leaderboard advertising
    06 Jul while the data was rebuilt on 02 Aug, in visible copy and in
    schema.org temporalCoverage."""
    print("\n[2] PUBLISHED FRESHNESS CLAIMS")
    art = ROOT / "assets/data/esg_quotient.json"
    if not art.exists():
        print("    skipped — no artifact")
        return
    try:
        doc = json.loads(art.read_text(encoding="utf-8"))
    except Exception as e:
        add("WARN", "claims", f"artifact unreadable: {e}")
        return
    truth = max((d for d in (parse_stamp(doc.get(k)) for k in
                             ("generated_at", "data_as_of", "data_cleaned_at")) if d),
                default=None)
    if not truth:
        add("WARN", "claims", "the artifact carries no parseable freshness stamp")
        return
    print(f"    artifact says: {truth}")
    hits = 0
    for name in ("esg-risk-leaderboard.html", "methodology.html", "index.html"):
        p = ROOT / name
        if not p.exists():
            continue
        t = p.read_text(encoding="utf-8", errors="replace")
        for pat, label in ((r"Data as of ([^.<]+)", "visible copy"),
                           (r'"temporalCoverage":\s*"([^"]+)"', "schema.org"),
                           (r"Last updated:\s*([^<]+)", "visible copy")):
            for m in re.finditer(pat, t):
                claim = m.group(1).strip()
                hits += 1
                d = parse_stamp(claim)
                if d and (truth - d).days > 1:
                    print(f"    {name:28} {label:12} '{claim}'  [STALE by {(truth-d).days}d]")
                    add("WARN", "claims",
                        f"{name} publishes '{claim}' ({label}) but the data is from "
                        f"{truth} — rebuild the page so the claim matches")
                else:
                    print(f"    {name:28} {label:12} '{claim}'")
    if not hits:
        print("    no freshness claims found")


# ── [3] BACKUP CLEARANCE ──────────────────────────────────────────────────────
def check_backups(apply_changes):
    print("\n[3] BACKUP CLEARANCE")
    root_res = ROOT.resolve()
    candidates = []
    for p in ROOT.rglob("*"):
        try:
            if not p.is_file() or p.is_symlink():
                continue
            if not is_backup(p):
                continue
            # Guard: must genuinely live under the site root once resolved.
            if root_res not in p.resolve().parents:
                add("WARN", "clearance",
                    f"skipped {p.name}: resolves outside {root_res}")
                continue
            candidates.append(p)
        except OSError:
            continue

    fams = {}
    for p in candidates:
        fams.setdefault(family_of(p), []).append(p)

    total = sum(f.stat().st_size for f in candidates if f.exists())
    print(f"    backup files: {len(candidates)} in {len(fams)} family(ies), "
          f"{total/1e6:.0f} MB")

    now = time.time()
    plan = []
    for fam, files in sorted(fams.items()):
        files.sort(key=lambda f: f.stat().st_mtime, reverse=True)   # newest first
        survivors = set(files[:KEEP_NEWEST])
        for f in files:
            age = (now - f.stat().st_mtime) / 86400
            if f in survivors:
                kept.append({"file": str(f), "age_days": round(age, 1),
                             "why": f"among the {KEEP_NEWEST} newest of its family"})
            elif age < MIN_AGE_DAYS:
                kept.append({"file": str(f), "age_days": round(age, 1),
                             "why": f"younger than {MIN_AGE_DAYS} days"})
            else:
                plan.append((f, age))

    plan.sort(key=lambda t: t[1], reverse=True)                     # oldest first
    if len(plan) > MAX_DELETE_PER_RUN:
        add("WARN", "clearance",
            f"{len(plan)} files qualify for clearance but this run is capped at "
            f"{MAX_DELETE_PER_RUN}; the rest go next run")
        plan = plan[:MAX_DELETE_PER_RUN]

    freed = 0
    for f, age in plan:
        size = f.stat().st_size
        if apply_changes:
            try:
                f.unlink()
                cleared.append({"file": str(f), "age_days": round(age, 1),
                                "bytes": size})
                freed += size
                print(f"    DELETED {f.name}  ({age:.0f}d, {size/1e6:.1f} MB)")
            except OSError as e:
                add("WARN", "clearance", f"could not delete {f}: {e}")
        else:
            cleared.append({"file": str(f), "age_days": round(age, 1),
                            "bytes": size, "dry_run": True})
            freed += size
            print(f"    WOULD DELETE {f.name}  ({age:.0f}d, {size/1e6:.1f} MB)")

    verb = "freed" if apply_changes else "would free"
    print(f"    kept {len(kept)}  |  {'cleared' if apply_changes else 'to clear'} "
          f"{len(plan)}  |  {verb} {freed/1e6:.0f} MB")
    if not apply_changes and plan:
        add("INFO", "clearance",
            f"{len(plan)} backup file(s) ({freed/1e6:.0f} MB) are eligible; "
            f"re-run with --apply to remove them")


# ── [4] DISK ──────────────────────────────────────────────────────────────────
def check_disk():
    print("\n[4] DISK")
    try:
        st = os.statvfs(str(ROOT))
    except (AttributeError, OSError):
        print("    skipped (not available on this platform)")
        return
    total = st.f_blocks * st.f_frsize
    free = st.f_bavail * st.f_frsize
    pct = 100.0 * (total - free) / total if total else 0
    print(f"    {pct:.0f}% used, {free/1e9:.1f} GB free of {total/1e9:.1f} GB")
    if pct >= 90:
        add("FAIL", "disk", f"disk {pct:.0f}% full — {free/1e9:.1f} GB free")
    elif pct >= 80:
        add("WARN", "disk", f"disk {pct:.0f}% full — {free/1e9:.1f} GB free")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true",
                    help="actually delete eligible backups (default: dry run)")
    ap.add_argument("--json", action="store_true")
    a = ap.parse_args()

    if not a.json:
        print("=" * 74)
        print(f"STALE-CONTENT CHECK  {dt.datetime.now(dt.timezone.utc):%Y-%m-%d %H:%M UTC}"
              f"   mode={'APPLY' if a.apply else 'DRY-RUN'}")
        print(f"root: {ROOT}")
        print("=" * 74)

    check_freshness()
    check_claims()
    check_backups(a.apply)
    check_disk()

    fails = [f for f in findings if f["level"] == "FAIL"]
    warns = [f for f in findings if f["level"] == "WARN"]
    result = {
        "ran_at": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"),
        "applied": a.apply, "fail": len(fails), "warn": len(warns),
        "cleared": cleared, "kept_count": len(kept), "findings": findings,
    }
    try:
        STATUS_OUT.parent.mkdir(parents=True, exist_ok=True)
        STATUS_OUT.write_text(json.dumps(result, indent=2), encoding="utf-8")
    except Exception:
        pass

    if a.json:
        print(json.dumps(result, indent=2))
    else:
        print("\n" + "=" * 74)
        print(f"VERDICT: {len(fails)} FAIL, {len(warns)} WARN, "
              f"{len(cleared)} file(s) {'cleared' if a.apply else 'eligible'}")
        for f in findings:
            print(f"  [{f['level']}] {f['check']}: {f['message']}")
        print("=" * 74)
    # Staleness is a nudge, not an outage: only a hard failure (disk) exits 1.
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
